### ISSUE TITLE
Snowflake External OAuth Integration Error after Upgrade to 0.62.0

### ISSUE THREAD

**Issue by tuhren** [Snowflake-Labs/terraform-provider-snowflake#1778]
**Provider Version**

0.62

**Describe the bug**

After upgrading to 0.62 (from 0.56) the terraform provider doesn't use quotes for the identifier. 

The provider generates:

DESCRIBE SECURITY INTEGRATION my_oauth_integration;

This fails due to missing quotes ("my_oauth_integration").

│ Error: error querying external oauth integration: 002003 (02000): SQL compilation error:
│ Integration 'MY_OAUTH_INTEGRATION' does not exist or not authorized.

**Expected behavior**

The provider should generate:

DESCRIBE SECURITY INTEGRATION "my_oauth_integration";

**Code samples and commands**

resource "snowflake_external_oauth_integration" "my_oauth_integration" {
  name = "my_oauth_integration"
  type = "CUSTOM"
  enabled = true
  ...
}

@sfc-gh-swinkler : I've already raised an Snowflake support case for this.
